version: '3.9'

services:
  store-app:
    image: store-app
    container_name: store-app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER_STREAM=new_user
      - WEATHER_HOST=http://weather:5050
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5051:5051'
