version: '3.9'

services:
  weather-app:
    image: weather-app
    container_name: weather-app
    hostname: weather
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEATHER_ENDPOINT=${WEATHER_ENDPOINT}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5050:5050'
