version: '3.9'

services:
  new-user-app:
    image: new-user-app
    container_name: new-user-app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER_STREAM=new_user
      - REDIS_RETRY_COUNT=10
      - PYTHONPATH=.
    build:
      context: .
      dockerfile: Dockerfile
